name: Move Resume PDF to docs/

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  move-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move PDF to docs folder
        run: |
          mkdir -p docs
          cp out/resume.pdf docs/resume.pdf

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/resume.pdf
          git commit -m "Update resume.pdf in docs [CI skip]" || echo "No changes to commit"
          git push
